development:
  bucket: famtivity/stage
  access_key_id: AKIAICPKGEIENKWK7B6Q
  secret_access_key: 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
test:
  bucket: bucket-test
  access_key_id: xxx
  secret_access_key: xxx
production:
  bucket: famtivity/production
  access_key_id: AKIAICPKGEIENKWK7B6Q
  secret_access_key: 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